services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tools_checker_app
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./static:/app/static
    env_file:
      - .env
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - UVICORN_WORKERS=1
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || curl -fsS http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    restart: unless-stopped

