
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    gzip:
      compress: {}

    healthz:
      replacePathRegex:
        regex: "^/healthz$"
        replacement: "/"
    
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: true
        referrerPolicy: "no-referrer"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"

    rate-limit:
      rateLimit:
        average: 50     
        burst: 100